name: textformfield_unit
description: A TextFormField with units.
version: 1.0.2
homepage: https://github.com/deakjahn/textformfield_unit

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
