name: textformfield_unit
description: A TextFormField with units.
version: 1.0.7
homepage: https://github.com/deakjahn/textformfield_unit

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

funding:
  - https://buymeacoffee.com/deakjahn

screenshots:
  - description: 'Example widget.'
    path: screenshots/screen.png

topics:
  - flutter
  - form
  - form-field