name: textformfield_unit
description: A TextFormField with units.
version: 1.0.1
homepage: https://github.com/deakjahn/textformfield_unit

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
